### ISSUE TITLE
Doesnt produce html file.

### ISSUE THREAD

**Issue by psmgeelen** [markfront/SinglePageFullHtml#2]
Hi there,

I am trying to make a copy of a local Dash (Plotly) website and it produces this error

```
page_url = http://192.168.178.57:8050
curr_dir = /home/pieter/SinglePageFullHtml/temp
file_stem = P-649027234
py_script: /home/pieter/SinglePageFullHtml/temp/GetFullWebPage.py
before merge file size: 0
page_url: http://192.168.178.57:8050
java.io.FileNotFoundException: /home/pieter/SinglePageFullHtml/temp/P-649027234.html (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.jsoup.helper.DataUtil.load(DataUtil.java:56)
	at org.jsoup.Jsoup.parse(Jsoup.java:88)
	at com.markfront.spfh.Utils.mergeIntoFatHtml(Utils.java:33)
	at com.markfront.spfh.SinglePageFullHtml.run(SinglePageFullHtml.java:99)
	at com.markfront.spfh.SinglePageFullHtml.main(SinglePageFullHtml.java:21)

result fat html saved to: /home/pieter/SinglePageFullHtml/temp/FP-649027234.html

result merged file size: 0

Time: 2.161sec
```
I am doing this on Linux, ubuntu 21.04 and I am a novice in Java..

I hope my specification is complete, 
thanks for considering
Pieter

**Comment by markfront** [comment]
Hi Pieter,

Thanks for using this lib. Have you tried it for other web pages? Did it not work at all, or only not work for the local site you mentioned?

Mark

**Comment by bhupesh** [comment]
I am also getting this error. I have tried with different urls.

Edit: I tried again after creating the file required in temp directory and it could find the file. However no data was saved in the file.
```
java -jar target\SinglePageFullHtml-1.0-SNAPSHOT-jar-with-dependencies.jar https://microsoft.com
page_url = https://microsoft.com
curr_dir = G:\SinglePageFullHtml\temp
file_stem = P1037439506
py_script: G:\SinglePageFullHtml\temp\GetFullWebPage.py
before merge file size: 0
page_url: https://microsoft.com
title:

css files:

javascript files:

img files:
css files: 0
js  files: 0
img files: 0

result fat html saved to: G:\SinglePageFullHtml\temp\FP1037439506.html

result merged file size: 44

Time: 2.512sec
```
